[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin_login_screen_1/code"
  to = "/admin_login_screen_1/code.html"
  status = 301

[[redirects]]
  from = "/student_authentication_screens_1/code"
  to = "/student_authentication_screens_1/code.html"
  status = 301

[[redirects]]
  from = "/course_player_interface_1/code"
  to = "/course_player_interface_1/code.html"
  status = 301

[[redirects]]
  from = "/quiz_interface_1/code"
  to = "/quiz_interface_1/code.html"
  status = 301

[[redirects]]
  from = "/admin_dashboard_1/code"
  to = "/admin_dashboard_1/code.html"
  status = 301

[[redirects]]
  from = "/course_management_screen_1/code"
  to = "/course_management_screen_1/code.html"
  status = 301

[[redirects]]
  from = "/student_management_screen_1/code"
  to = "/student_management_screen_1/code.html"
  status = 301

[[redirects]]
  from = "/quiz_management_screen_1/code"
  to = "/quiz_management_screen_1/code.html"
  status = 301

[[redirects]]
  from = "/order_management_screen_1/code"
  to = "/order_management_screen_1/code.html"
  status = 301

[[redirects]]
  from = "/my_dashboard_(student)_1/code"
  to = "/my_dashboard_(student)_1/code.html"
  status = 301

[[redirects]]
  from = "/my_profile_(student)_1/code"
  to = "/my_profile_(student)_1/code.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

